-- CATALOG upsert
insert into cosme_check.catalog
(ean,brand,name,category,image_url,source_url,score,score_label,score_tone,count_total,ingredients_text,is_active,count_orange,count_rouge,search_norm,search_key) values
('3770035517008','Vagance','Le Spray capillaire','coiffure/soin-capillaire/demelant-sans-rincage','https://rogesnduejmqpxolhbif.supabase.co/storage/v1/object/public/cosmetwiki-products/3770035517008.webp','https://vagance.eco/products/spray-capillaire-hydratant-cheveux-boucles-naturel',15.92,'Bien','green',8,'Aqua, Lavandula Angustifolia Flower Water, Urtica Dioica Leaf Extract, Cananga Odorata Flower Water, Aloe Barbadensis Leaf Juice, Potassium Sorbate, Sodium Benzoate, Citric Acid',true,0,0,'vagance le spray capillaire','vagance le spray capillaire'),
('3770035517015','Vagance','La Crème Capillaire','coiffure/soin-capillaire/soin-cheveux-boucles','https://rogesnduejmqpxolhbif.supabase.co/storage/v1/object/public/cosmetwiki-products/3770035517015.webp','https://vagance.eco/products/creme-capillaire-nourrissante-cheveux-boucles-frises',16.45,'Bien','green',14,'Aqua, Cananga Odorata Flower Water, Persea Gratissima Oil, Mangifera Indica Seed Butter, Brassica Alcohol, Coco-Caprylate/Caprate, Erythritol, Brassicyl Valinate Esylate, Calcium Gluconate, Potassium sorbate, Sodium Benzoate, Tocopherol, Helianthus Annuus Seed Oil, Citric acid',true,0,0,'vagance la creme capillaire','vagance la creme capillaire'),
('3770035517022','Vagance','Le Masque Capillaire','coiffure/soin-capillaire/masque-capillaire','https://rogesnduejmqpxolhbif.supabase.co/storage/v1/object/public/cosmetwiki-products/3770035517022.webp','https://vagance.eco/products/masque-capillaire-bio-reparateur-cheveux-secs',16.45,'Bien','green',14,'Aqua, Cananga Odorata Flower Water, Butyrospermum Parkii Butter, Mangifera Indica Seed Butter, Brassica Alcohol, Coco-Caprylate/Caprate, Erythritol, Brassicyl Valinate Esylate, Calcium Gluconate, Hydrolyzed Rice Protein, Sodium Benzoate, Potassium Sorbate, Tocopherol, Helianthus Annuus Seed Oil',true,0,0,'vagance le masque capillaire','vagance le masque capillaire'),
('3770035517039','Vagance','L’Huile Soin Barbe','rasage-et-epilation/soin-de-la-barbe/huile-a-barbe','https://rogesnduejmqpxolhbif.supabase.co/storage/v1/object/public/cosmetwiki-products/3770035517039.webp','https://vagance.eco/products/huile-barbe-naturelle-hydratante-made-in-france',16.58,'Bien','green',6,'Cannabis Sativa Seed Oil, Ricinus Communis Seed Oil, Brassica Oleracea Italica Seed Oil, Tocopherol, Helianthus Annuus Seed Oil, Cedrus Atlantica Bark Oil',true,0,0,'vagance l’huile soin barbe','vagance l huile soin barbe'),
('3770035517046','Vagance','L’Huile Soin Barbe (recharge)','rasage-et-epilation/soin-de-la-barbe/huile-a-barbe','https://rogesnduejmqpxolhbif.supabase.co/storage/v1/object/public/cosmetwiki-products/3770035517046.webp','https://vagance.eco/products/huile-barbe-naturelle-hydratante-made-in-france',16.58,'Bien','green',6,'Cannabis Sativa Seed Oil, Ricinus Communis Seed Oil, Brassica Oleracea Italica Seed Oil, Tocopherol, Helianthus Annuus Seed Oil, Cedrus Atlantica Bark Oil',false,0,0,'vagance l’huile soin barbe (recharge)','vagance l huile soin barbe recharge'),
('3770035517053','Vagance','Le Masque Capillaire (recharge)','coiffure/soin-capillaire/masque-capillaire','https://rogesnduejmqpxolhbif.supabase.co/storage/v1/object/public/cosmetwiki-products/3770035517053.webp','https://vagance.eco/products/masque-capillaire-bio-reparateur-cheveux-secs',16.45,'Bien','green',14,'Aqua, Cananga Odorata Flower Water, Butyrospermum Parkii Butter, Mangifera Indica Seed Butter, Brassica Alcohol, Coco-Caprylate/Caprate, Erythritol, Brassicyl Valinate Esylate, Calcium Gluconate, Hydrolyzed Rice Protein, Sodium Benzoate, Potassium Sorbate, Tocopherol, Helianthus Annuus Seed Oil',false,0,0,'vagance le masque capillaire (recharge)','vagance le masque capillaire recharge'),
('3770035517060','Vagance','La Crème Capillaire (recharge)','coiffure/soin-capillaire/soin-cheveux-boucles','https://rogesnduejmqpxolhbif.supabase.co/storage/v1/object/public/cosmetwiki-products/3770035517060.webp','https://vagance.eco/products/creme-capillaire-nourrissante-cheveux-boucles-frises',16.45,'Bien','green',14,'Aqua, Cananga Odorata Flower Water, Persea Gratissima Oil, Mangifera Indica Seed Butter, Brassica Alcohol, Coco-Caprylate/Caprate, Erythritol, Brassicyl Valinate Esylate, Calcium Gluconate, Potassium sorbate, Sodium Benzoate, Tocopherol, Helianthus Annuus Seed Oil, Citric acid',false,0,0,'vagance la creme capillaire (recharge)','vagance la creme capillaire recharge'),
('3770035517077','Vagance','Le Spray capillaire (recharge)','coiffure/soin-capillaire/demelant-sans-rincage','https://rogesnduejmqpxolhbif.supabase.co/storage/v1/object/public/cosmetwiki-products/3770035517077.webp','https://vagance.eco/products/spray-capillaire-hydratant-cheveux-boucles-naturel',15.92,'Bien','green',8,'Aqua, Lavandula Angustifolia Flower Water, Urtica Dioica Leaf Extract, Cananga Odorata Flower Water, Aloe Barbadensis Leaf Juice, Potassium Sorbate, Sodium Benzoate, Citric Acid',false,0,0,'vagance le spray capillaire (recharge)','vagance le spray capillaire recharge'),
('3770035517084','Vagance','Le Shampoing capillaire et barbe','coiffure/shampooing/shampooing-cheveux-boucles','https://rogesnduejmqpxolhbif.supabase.co/storage/v1/object/public/cosmetwiki-products/3770035517084.webp','https://vagance.eco/products/shampoing-naturel-hydratant-cheveux-boucles-barbe',16.3,'Bien','green',13,'Aqua, Urtica Dioica Leaf Water, Cananga Odorata Flower Water, Aloe Barbadensis Leaf Juice, Decyl Glucoside, Sodium Cocoyl Glutamate, Persea Gratissima Oil, Xanthan Gum, Potassium Sorbate, Sodium Benzoate, Propylene Glycol, Citric Acid, Hydrolyzed Rice Protein',true,0,0,'vagance le shampoing capillaire et barbe','vagance le shampoing capillaire et barbe'),
('3770035517091','Vagance','Le Shampoing capillaire et barbe (recharge)','coiffure/shampooing/shampooing-cheveux-boucles','https://rogesnduejmqpxolhbif.supabase.co/storage/v1/object/public/cosmetwiki-products/3770035517091.webp','https://vagance.eco/products/shampoing-naturel-hydratant-cheveux-boucles-barbe',16.3,'Bien','green',13,'Aqua, Urtica Dioica Leaf Water, Cananga Odorata Flower Water, Aloe Barbadensis Leaf Juice, Decyl Glucoside, Sodium Cocoyl Glutamate, Persea Gratissima Oil, Xanthan Gum, Potassium Sorbate, Sodium Benzoate, Propylene Glycol, Citric Acid, Hydrolyzed Rice Protein',false,0,0,'vagance le shampoing capillaire et barbe (recharge)','vagance le shampoing capillaire et barbe recharge')
on conflict (ean) do update set
 brand=excluded.brand,name=excluded.name,category=excluded.category,image_url=excluded.image_url,
 source_url=excluded.source_url,score=excluded.score,score_label=excluded.score_label,score_tone=excluded.score_tone,
 count_total=excluded.count_total,ingredients_text=excluded.ingredients_text,is_active=excluded.is_active,
 count_orange=excluded.count_orange,count_rouge=excluded.count_rouge,search_norm=excluded.search_norm,search_key=excluded.search_key;

-- CLASSIFICATIONS upsert
insert into cosme_check.product_classifications
(ean,category,subcategory,subsubcategory,category_slug,method,confidence,gpt_verified,score,count_total) values
('3770035517008','Coiffure','Soin capillaire','Démêlant (sans rinçage)','coiffure/soin-capillaire/demelant-sans-rincage','manual',1.0,true,15.92,8),
('3770035517015','Coiffure','Soin capillaire','Soin pour cheveux bouclés','coiffure/soin-capillaire/soin-cheveux-boucles','manual',1.0,true,16.45,14),
('3770035517022','Coiffure','Soin capillaire','Masque capillaire','coiffure/soin-capillaire/masque-capillaire','manual',1.0,true,16.45,14),
('3770035517039','Rasage et épilation','Soin de la barbe','Huile à barbe','rasage-et-epilation/soin-de-la-barbe/huile-a-barbe','manual',1.0,true,16.58,6),
('3770035517046','Rasage et épilation','Soin de la barbe','Huile à barbe','rasage-et-epilation/soin-de-la-barbe/huile-a-barbe','manual',1.0,true,16.58,6),
('3770035517053','Coiffure','Soin capillaire','Masque capillaire','coiffure/soin-capillaire/masque-capillaire','manual',1.0,true,16.45,14),
('3770035517060','Coiffure','Soin capillaire','Soin pour cheveux bouclés','coiffure/soin-capillaire/soin-cheveux-boucles','manual',1.0,true,16.45,14),
('3770035517077','Coiffure','Soin capillaire','Démêlant (sans rinçage)','coiffure/soin-capillaire/demelant-sans-rincage','manual',1.0,true,15.92,8),
('3770035517084','Coiffure','Shampooing','Shampooing cheveux bouclés','coiffure/shampooing/shampooing-cheveux-boucles','manual',1.0,true,16.3,13),
('3770035517091','Coiffure','Shampooing','Shampooing cheveux bouclés','coiffure/shampooing/shampooing-cheveux-boucles','manual',1.0,true,16.3,13)
on conflict (ean) do update set
 category=excluded.category,subcategory=excluded.subcategory,subsubcategory=excluded.subsubcategory,
 category_slug=excluded.category_slug,method=excluded.method,confidence=excluded.confidence,
 gpt_verified=excluded.gpt_verified,score=excluded.score,count_total=excluded.count_total,updated_at=now();
